version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            code-network:
              - nginx
              - web
    php:
        # image: php:fpm
        build:
          context: ./php-fpm/
          dockerfile: Dockerfile
        volumes:
            - ./code:/code
            - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        networks:
            code-network:
              - php
              - phpserver
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P4ssw0rd1!
            MYSQL_DATABASE: ethics-canvas
            MYSQL_USER: dbadmin
            MYSQL_PASSWORD: P4ssw0rd1!
        networks:
           code-network:
             - db

networks:
    code-network:
        driver: bridge

volumes:
    db_data:
