version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        # image: php:fpm
        build: .
        dockerfile: php-fpm/Dockerfile
        volumes:
            - ./code:/code
            - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        networks:
            - code-network
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P4ssw0rd1!
            MYSQL_DATABASE: ethics-canvas
            MYSQL_USER: dbadmin
            MYSQL_PASSWORD: P4ssw0rd1!
#       networks:
#            - code-network

networks:
    code-network:
        driver: bridge

volumes:
    db_data:
